import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import static org.junit.Assert.*;

/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
public class gmailLoginLogOutTests {
  private static final By EMAIL_INPUT = By.id("Email");
  private static final By PASSWORD_INPUT = By.id("Passwd");
  private static final By NEXT_BUTTON = By.id("next");
  private static final By SIGN_BUTTON = By.id("signIn");
  private static final By USER_SETTINGS = 
      By.xpath(".//*[@id='gb']/div[1]/div[1]/div[2]/div[4]/div[1]/a/span");
  private static final By USER_SIGNOUT = By.id("gb_71");

  public static void main (String args[]) throws Exception{

    WebDriver driver = new FirefoxDriver();
    driver.get("http://gmail.com");
    testInvalidGmailID(driver);
    testInvalidPassword(driver);
    testGmailLogin(driver);
    testGmailLogOut(driver);
  }
  // Check error message when invalid GMail ID entered.
  public static void testInvalidGmailID(WebDriver driver) throws Exception{
    WebElement userNameTextBox = driver.findElement(EMAIL_INPUT);
    userNameTextBox.sendKeys("testtest!!");
    driver.findElement(NEXT_BUTTON).click();
    Thread.sleep(100);
    WebElement errorMsgEmail = driver.findElement(By.xpath(".//*[@id='errormsg_0_Email']"));
    assertEquals("Emal id not matched.", "Sorry, Google doesn't recognize that email.", 
        errorMsgEmail.getText());
    userNameTextBox.clear();
  }

  // Check error message when invalid GMail password entered.
  public static void testInvalidPassword(WebDriver driver) throws Exception{
    WebElement userNameTextBox = driver.findElement(EMAIL_INPUT);
    //TODO When running replace with '<EnterMailID>' with correct password.
    userNameTextBox.sendKeys("<EnterMailID>");
    driver.findElement(NEXT_BUTTON).click();
    Thread.sleep(100);
    WebElement passwordTextBox = driver.findElement(PASSWORD_INPUT);       
    passwordTextBox.sendKeys("testtest1sdfsdf");
    driver.findElement(SIGN_BUTTON).click();
    Thread.sleep(100);
    WebElement errorMsgPassword = driver.findElement(By.xpath(".//*[@id='errormsg_0_Passwd']"));
    assertEquals("Emal and Password didn't matched", "The email and password you entered "
        + "don't match.", errorMsgPassword.getText());
  }

  // Check Gmail login successfully with valid email id. 
  public static void testGmailLogin(WebDriver driver) throws Exception{
    WebElement passwordTextBox = driver.findElement(PASSWORD_INPUT);
    //TODO When running replace with '<EnterPassword>' with correct password.
    passwordTextBox.sendKeys("<EnterPassword>");
    driver.findElement(SIGN_BUTTON).click();
    Thread.sleep(1000);
    //After login into GMail checking GMail drop down is present or not.
    WebElement gmailDropBox = driver.findElement(By.xpath(".//*[@id=':j']/span"));
    assertEquals("Emal and Password didn't matched", "Gmail", gmailDropBox.getText());
  }

  // Check GMail Logout after successful login account.
  public static void testGmailLogOut(WebDriver driver) throws Exception{
    Thread.sleep(100);
    WebElement userSettings = driver.findElement(USER_SETTINGS);        
    userSettings.click();
    WebElement userLogOut = driver.findElement(USER_SIGNOUT);
    userLogOut.click();
  }
}